spring:
  application:
    name: traininglog

  datasource:
    url: jdbc:h2:mem:traininglogdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true
